In [2]:
import pandas as pd
import numpy as np

In [4]:
#Membuat Series

nilai = pd.Series([90,85,75,100])
print(nilai)

0     90
1     85
2     75
3    100
dtype: int64

In [6]:
nama = pd.Series(["Andi","Budi","Ayam"])
print(nama)

0    Andi
1    Budi
2    Ayam
dtype: object

In [9]:
#Membuat Data Frame

data = {
    "Nama":["Andi","Budi","Ayam"],
    "Umur":[20,21,22],
    "Kota":["Medan","Jakarta","Bandung"]
}

df = pd.DataFrame(data)
print(df)

   Nama  Umur     Kota
0  Andi    20    Medan
1  Budi    21  Jakarta
2  Ayam    22  Bandung

In [13]:
#Membaca dataset

df = pd.read_csv("StudyCase - Anggota_Perpus.csv")
print(df)

#Mencari Informasi terkait Data

df.head()
df.tail()
df.info()
df.describe()

      ID_Anggota Nama_Anggota                        Alamat       No.Telepon
0         123876      Abagael              Garibaldi Avenue   (021) - 428604
1         123877      Abagail                         81 St   (021) - 428605
2         123878         Abbe                        Elm Dr   (021) - 428606
3         123879        Abbey                        193 St   (021) - 428607
4         123880         Abbi              Fairchild Avenue   (021) - 428608
...          ...          ...                           ...              ...
3700      127576         Nata            Southern Boulevard  (021) - 5645777
3701      127577       Natala  Monsignor Paul M Andrews Way  (021) - 5645778
3702      127578      Natalee                     Waring Av  (021) - 5645779
3703      127579      Natalia                     Boston Rd  (021) - 5645780
3704      127580      Natalie                         53 Av  (021) - 5645781

[3705 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3705 entries, 0 to 3704
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID_Anggota    3705 non-null   int64
 1   Nama_Anggota  3705 non-null   object
 2   Alamat        3705 non-null   object
 3   No.Telepon    3705 non-null   object
dtypes: int64(1), object(3)
memory usage: 115.9+ KB

          ID_Anggota
count    3705.000000
mean   125728.000000
std      1069.685702
min    123876.000000
25%    124802.000000
50%    125728.000000
75%    126654.000000
max    127580.000000

In [16]:
#Mengakses Data

df["Nama_Anggota"]
df[["Alamat","No.Telepon"]]
df.iloc[0]
df.iloc[0:5]
df.loc[0]

ID_Anggota                123876
Nama_Anggota             Abagael
Alamat          Garibaldi Avenue
No.Telepon        (021) - 428604
Name: 0, dtype: object

In [20]:


df.drop("Nama_Anggota",axis=1)

df.rename(columns={
    "Nama_Anggota":"Name"
})

      ID_Anggota     Name                        Alamat       No.Telepon
0         123876  Abagael              Garibaldi Avenue   (021) - 428604
1         123877  Abagail                         81 St   (021) - 428605
2         123878     Abbe                        Elm Dr   (021) - 428606
3         123879    Abbey                        193 St   (021) - 428607
4         123880     Abbi              Fairchild Avenue   (021) - 428608
...          ...      ...                           ...              ...
3700      127576     Nata            Southern Boulevard  (021) - 5645777
3701      127577   Natala  Monsignor Paul M Andrews Way  (021) - 5645778
3702      127578  Natalee                     Waring Av  (021) - 5645779
3703      127579  Natalia                     Boston Rd  (021) - 5645780
3704      127580  Natalie                         53 Av  (021) - 5645781

[3705 rows x 4 columns]

In [21]:
df.duplicated()

df.drop_duplicates()

0       False
1       False
2       False
3       False
4       False
        ...
3700    False
3701    False
3702    False
3703    False
3704    False
Length: 3705, dtype: bool

In [22]:
#Menangani Missing Value

df.isnull()

      ID_Anggota  Nama_Anggota  Alamat  No.Telepon
0          False         False   False       False
1          False         False   False       False
2          False         False   False       False
3          False         False   False       False
4          False         False   False       False
...          ...           ...     ...         ...
3700       False         False   False       False
3701       False         False   False       False
3702       False         False   False       False
3703       False         False   False       False
3704       False         False   False       False

[3705 rows x 4 columns]

In [23]:
df.isnull().sum()

ID_Anggota      0
Nama_Anggota    0
Alamat          0
No.Telepon      0
dtype: int64

In [25]:
#Menangani Nilai Duplikat

df("No.Telepon") = df["No.Telepon"].fillna(
    df["No.Telepon"].mean()
)

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (638089328.py, line 3)